apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml

namespace: example-application

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: example-application
